##
# @author Luca-Philipp Grumbach
#
# # Description
# Collects sources for a build.
##
Import("env")

# gather sources
l_sources = [
    "entities/Player.cpp",
    "gfx/Animation.cpp",
    "world/tiles/Tile.cpp",
    "world/tiles/TileRegistry.cpp",
    "world/Generator.cpp",
    "world/Map.cpp",
]

for l_so in l_sources:
    env.sources.append(env.Object(l_so))

env.standalone = env.Object("Game.cpp")

Export("env")
