name: Build and Publish Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make dependencies-${{ matrix.os }}

      - name: Compile Project
        run: make release=1

      - name: Copy assets
        run: make release=1 copyassets

      - name: Create Release
        uses: actions/create-release@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} - ${{ matrix.os }}
          draft: false
          prerelease: false
