name: Release MacOS

on:
  release:
  workflow_dispatch:

jobs:
  build-and-publish-macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Compile project
        run:  make

      - name: Copy assets
        run: make copyassets

      - name: Clean directory
        run: make clean
  
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'macOS.zip'
          path: './bin/macOS'
         
      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Publish macOS binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: macOS.zip
          asset_name: macOS-binaries.zip
          tag: ${{ steps.get-latest-tag.outputs.tag }}
          overwrite: true

