name: Release Windows

on:
  push:
    tags: [ '*' ]

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Compile project
        run:  make

      - name: Copy assets
        shell: pwsh
        run: make copyassets

      - name: Clean directory
        run: make clean
  
      - name: Archive release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'windows.zip'
          path: './bin/windows64'

      - name: Publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows.zip
          asset_name: windows-binaries.zip
          tag: ${{  github.ref_name }}
          overwrite: true

